connections:
dbt_glue_demo:
  outputs:
    dev:
      type: glue
      role_arn: arn:aws:iam::<>:role/GlueInteractiveSessionRole
      region: us-east-1
      workers: 3
      worker_type: G.1X
      schema: "default"
      session_provisioning_timeout_in_seconds: 200
      glue_session_reuse: True
      datalake_formats: "hudi"
      location: "s3://<BUCKET>/dbt/"
      conf: spark.serializer=org.apache.spark.serializer.KryoSerializer  --conf spark.sql.hive.convertMetastoreParquet=false --conf spark.sql.hive.convertMetastoreParquet=false --conf spark.sql.catalog.spark_catalog=org.apache.spark.sql.hudi.catalog.HoodieCatalog --conf spark.sql.legacy.pathOptionBehavior.enabled=true --conf spark.sql.extensions=org.apache.spark.sql.hudi.HoodieSparkSessionExtension

  target: dev